[package]
name = "krpc-mars"
version = "0.8.0"
authors = ["cahu"]
build = "build.rs"
license = "GPL-3.0"
edition = "2021"

[dependencies]
protobuf = "3.2.0"
thiserror = "1.0.39"

[build-dependencies]
protobuf-codegen = "3.2.0"
